include:
#  - board: nice_nano_v2
#    shield: cheapinov2
#    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lily58_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

#    snippet: zmk-usb-logging

  ## reset firmware
  - board: nice_nano_v2
    shield: settings_reset
